targets:
  $default:
    builders:
      json_serializable:
        enabled: true
        generate_for:
          include:
            - lib/models/**.dart
      kiwi_generator:
        enabled: true
        generate_for:
          include:
            - lib/config/**.dart
      source_gen|combining_builder:
        options:
          build_extensions:
            '^lib/{{}}.dart': 'lib/generated/{{}}.g.dart'