targets:
  $default:
    builders:
      json_serializable:
        enabled: true
        generate_for:
          include:
            - lib/models/**.dart
      source_gen|combining_builder:
        options:
          build_extensions:
            '^lib/{{}}.dart': 'lib/generated/{{}}.g.dart'
      freezed:
        enabled: true
        generate_for:
          include:
            - lib/models/**.dart
        options:
          build_extensions:
            '^lib/models/{{}}.dart': 'lib/generated/models/{{}}.freezed.dart'