name: dart_server
description: A HTTP Dart Server Template
version: 1.0.0

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  shelf_cors_headers: ^0.1.4
  shelf_plus: ^1.5.0

dev_dependencies:
  lints: ^2.0.1