name: dart_server
description: A HTTP Dart Server Template
version: 1.0.0

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  crypto: ^3.0.2
  encrypt: ^5.0.1
  equatable: ^2.0.5
  fpdart: ^0.3.0
  json_annotation: ^4.7.0
  kiwi: ^4.0.3
  logger: ^1.1.0
  path: ^1.8.2
  sembast: ^3.3.1
  shelf_cors_headers: ^0.1.4
  shelf_plus: ^1.5.0
  system_info2: ^2.0.4

dev_dependencies:
  build_runner: ^2.3.2
  http: ^0.13.5
  json_serializable: ^6.5.4
  kiwi_generator: ^4.0.3
  lints: ^2.0.1
  source_gen: ^1.2.6