name: dart_server
description: A HTTP Dart Server Template
version: 1.0.0

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  crypto: ^3.0.2
  encrypt: ^5.0.1
  fpdart: ^0.3.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  injectable: ^2.1.0
  json_annotation: ^4.7.0
  logger: ^1.1.0
  path: ^1.8.3
  sembast: ^3.3.1
  shelf_cors_headers: ^0.1.4
  shelf_plus: ^1.5.0
  system_info2: ^2.0.4

dev_dependencies:
  build_runner: ^2.3.2
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  injectable_generator: ^2.1.3
  lints: ^2.0.1